name       : ruby-net-sftp
version    : 2.1.2
release    : 1
source     :
    - https://rubygems.org/downloads/net-sftp-2.1.2.gem : 3e70b8130b1c86039b0847aeb088a2254df49053023546a5923e5763c923c710
license    : MIT
component  : programming.ruby
summary    : RubyGem - net-sftp
description: |
    A pure Ruby implementation of the SFTP client protocol.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby-net-ssh
install    : |
    %gem_install
